# Generated by Django 3.0.8 on 2020-08-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
